#!/usr/bin/env python3
"""Generate epub-credits.tex: credit lines for third-party figures, from the
abstract/author fields of the two 00_METADATA.bib files. Book-native figures
(Hildebrand/Fravel) get no credit line, matching the print edition policy."""
import re, os, glob
from pathlib import Path
BUILD = Path(__file__).resolve().parent.parent
BASE = BUILD.parent / "Intro-Math-Programming" / "baseText"
def parse_bib(path):
    txt = "\n".join(l for l in open(path).read().splitlines()
                    if not l.lstrip().startswith("%"))
    out = {}
    for m in re.finditer(r"@\w+\{([^,]+),", txt):
        key = m.group(1).strip(); start = m.end(); d = 1; i = start
        while i < len(txt) and d > 0:
            if txt[i] == "{": d += 1
            elif txt[i] == "}": d -= 1
            i += 1
        body = txt[start:i-1]; fields = {}
        for fm in re.finditer(r"(\w+)\s*=\s*\{", body):
            j = fm.end(); dd = 1; k = j
            while k < len(body) and dd > 0:
                if body[k] == "{": dd += 1
                elif body[k] == "}": dd -= 1
                k += 1
            fields[fm.group(1).lower()] = " ".join(body[j:k-1].split())
        out[key] = fields
    return out
bibs = {}
for bp in ["optimization/figures/figures-static/00_METADATA.bib",
           "optimization/figures/figures-source/00_METADATA.bib"]:
    bibs.update(parse_bib(BASE / bp))
OWN = re.compile(r"Hildebrand|Fravel|Screenshot")
lines = ["% Auto-generated by tools/gen-credits.py - do not edit.",
         "\\makeatletter"]
n = 0
for img in sorted(glob.glob(str(BUILD / "figs-conv/*"))):
    base = os.path.splitext(os.path.basename(img))[0]
    entry = None
    for cand in (base, base+".png", base+".jpg", base+".pdf", base+".JPG",
                 "tikz/"+base, "tikz/"+base+".pdf"):
        if cand in bibs: entry = bibs[cand]; break
    if not entry: continue
    author = entry.get("author", "")
    if not author or OWN.search(author): continue
    a = re.sub(r"\\href\{[^}]*\}\{([^}]*)\}", r"\1", author)
    a = re.sub(r"\\\w+", "", a).replace("{", "").replace("}", "").strip().rstrip(".,")
    url = entry.get("url", "").split("#")[0]   # no # in macro definitions
    credit = f"Image: {a}." + (f" \\url{{{url}}}" if url else "")
    lines.append("\\expandafter\\def\\csname figcredit@%s\\endcsname{%s}" % (base, credit))
    n += 1
lines.append("\\makeatother")
(BUILD / "epub-credits.tex").write_text("\n".join(lines) + "\n")
print("credits:", n)
