
name: CI-check-latex

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: install texlive
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          texlive latexmk texlive-latex-extra texlive-science texlive-fonts-extra \
          texlive-extra-utils texlive-bibtex-extra biber
    - name: make check
      run: make check
    - name: Get product file name
      id: get_product_info
      run: |
        echo "file_path=$(make list-products | head -n1)" >> "$GITHUB_OUTPUT"
        echo "file_name=$(basename $(make list-products | head -n1))" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.get_product_info.outputs.file_path }}
        name: ${{ steps.get_product_info.outputs.file_name }}
